import type { JobRequest } from "./types";

export const MOCK_JOB_REQUESTS: JobRequest[] = [
  {
    id: "job-pesh-101",
    category: "Electrician",
    subCategory: "Main DB Breaker & Short Circuit",
    title: "Main DB Breaker Tripping & UPS Inverter Line Sparking",
    description:
      "Our main distribution board breaker keeps tripping whenever the AC and water pump turn on together. There is also a burning smell near the UPS inverter connection in the corridor.",
    distance: "1.8 km",
    locationArea: "Hayatabad, Peshawar",
    fullAddress: "House 42-B, Sector D-1, Phase 3, Hayatabad, Peshawar",
    uploadedTime: "12 min ago",
    postedTimestamp: Date.now() - 12 * 60 * 1000,
    suggestedVisitCharge: 500,
    preferredTiming: "Today, 4:00 PM – 6:00 PM",
    status: "URGENT",
    customer: {
      firstName: "Ahmed",
      fullName: "Ahmed Khan Bangash",
      avatarUrl: "/landing/ahmad-khan-avatar-alt.png",
      rating: 4.8,
      reviewCount: 18,
      totalOrders: 24,
      isVerified: true,
      memberSince: "Nov 2024",
    },
    images: ["/landing/db-panel-wiring.png", "/landing/electrician-db-technician.png"],
    voiceNote: {
      durationFormatted: "0:38",
      durationSeconds: 38,
      waveformPattern: [35, 60, 45, 80, 95, 65, 40, 75, 90, 85, 50, 70, 40, 60, 30],
    },
  },
  {
    id: "job-pesh-102",
    category: "Plumber",
    subCategory: "Underground Pipe Leakage & Geyser Valve",
    title: "Bathroom Concealed Pipe Leakage Damaging Bedroom Wall",
    description:
      "Water is seeping through the master bathroom tile grout and creating moisture patches on the adjoining bedroom wall. Need urgent inspection with pressure test gauge.",
    distance: "2.4 km",
    locationArea: "University Town, Peshawar",
    fullAddress: "Lane 7, Circular Road, University Town, Peshawar",
    uploadedTime: "25 min ago",
    postedTimestamp: Date.now() - 25 * 60 * 1000,
    suggestedVisitCharge: 600,
    preferredTiming: "Today, Within 2 Hours",
    status: "OPEN",
    customer: {
      firstName: "Usman",
      fullName: "Usman Tariq",
      avatarUrl: "/landing/pro-avatar-1-alt.png",
      rating: 4.9,
      reviewCount: 12,
      totalOrders: 16,
      isVerified: true,
      memberSince: "Jan 2025",
    },
    images: ["/landing/plumbing-leakage-alt.png", "/landing/water-tank-disinfection.png"],
    voiceNote: {
      durationFormatted: "0:45",
      durationSeconds: 45,
      waveformPattern: [25, 45, 70, 85, 60, 40, 65, 80, 100, 75, 55, 35, 65, 50, 30],
    },
  },
  {
    id: "job-pesh-103",
    category: "AC Technician",
    subCategory: "1.5 Ton Inverter AC Cooling & Gas Leak",
    title: "1.5 Ton Dawlance Inverter AC Not Cooling (Error Code E3)",
    description:
      "The indoor blower is running but outdoor unit compressor stops after 5 minutes with E3 error code. Needs outdoor coil inspection, manifold gauge test, and gas pressure check.",
    distance: "3.1 km",
    locationArea: "Saddar, Peshawar",
    fullAddress: "Flat 402, Al-Jannat Plaza, Saddar Road, Peshawar Cantt",
    uploadedTime: "40 min ago",
    postedTimestamp: Date.now() - 40 * 60 * 1000,
    suggestedVisitCharge: 500,
    preferredTiming: "Tomorrow Morning, 10:00 AM",
    status: "OPEN",
    customer: {
      firstName: "Bilal",
      fullName: "Bilal Afridi",
      avatarUrl: "/landing/bilal-tariq-avatar-alt.png",
      rating: 4.7,
      reviewCount: 22,
      totalOrders: 31,
      isVerified: true,
      memberSince: "Sep 2024",
    },
    images: ["/landing/ac-deep-wash-alt.png", "/landing/solar-inverter.png"],
    voiceNote: {
      durationFormatted: "0:29",
      durationSeconds: 29,
      waveformPattern: [40, 70, 50, 90, 80, 60, 45, 85, 95, 60, 40, 55, 35, 25, 20],
    },
  },
  {
    id: "job-pesh-104",
    category: "Solar Technician",
    subCategory: "6kW Hybrid Inverter & Battery Bank",
    title: "6kW Inverex Hybrid Inverter Grid Overvoltage Fault",
    description:
      "Solar inverter is tripping on over-voltage fault during peak daylight hours. Need net-metering line balance check, DC breaker test, and tubular battery terminal cleaning.",
    distance: "4.5 km",
    locationArea: "Ring Road, Peshawar",
    fullAddress: "Near Achini Chowk, Ring Road, Peshawar",
    uploadedTime: "1 hour ago",
    postedTimestamp: Date.now() - 60 * 60 * 1000,
    suggestedVisitCharge: 800,
    preferredTiming: "Today, 5:30 PM",
    status: "OPEN",
    customer: {
      firstName: "Maryam",
      fullName: "Maryam Nawaz",
      avatarUrl: "/landing/maryam-nawaz-alt.png",
      rating: 5.0,
      reviewCount: 9,
      totalOrders: 11,
      isVerified: true,
      memberSince: "Feb 2025",
    },
    images: ["/landing/solar-inverter.png", "/landing/db-panel-wiring.png"],
    voiceNote: {
      durationFormatted: "0:52",
      durationSeconds: 52,
      waveformPattern: [30, 50, 75, 90, 85, 65, 45, 80, 100, 90, 70, 50, 40, 60, 35],
    },
  },
  {
    id: "job-pesh-105",
    category: "Carpenter",
    subCategory: "Hydraulic Hinges & Sliding Wardrobe Track",
    title: "Modular Kitchen Cabinet Hydraulic Hinges & Drawer Channel Replacement",
    description:
      "Two overhead hydraulic lift cabinets fell off their alignment and the soft-close drawer channel under sink is stuck due to rusted ball bearings.",
    distance: "2.9 km",
    locationArea: "Gulbahar, Peshawar",
    fullAddress: "Street 2, Gulbahar No. 4, Peshawar",
    uploadedTime: "2 hours ago",
    postedTimestamp: Date.now() - 120 * 60 * 1000,
    suggestedVisitCharge: 400,
    preferredTiming: "Tomorrow, 2:00 PM – 4:00 PM",
    status: "OPEN",
    customer: {
      firstName: "Farhan",
      fullName: "Farhan Shinwari",
      avatarUrl: "/landing/pro-avatar-2-alt.png",
      rating: 4.6,
      reviewCount: 14,
      totalOrders: 19,
      isVerified: false,
      memberSince: "Dec 2024",
    },
    images: ["/landing/kitchen-cabinetry-alt.png", "/landing/house-painting-alt.png"],
    voiceNote: {
      durationFormatted: "0:34",
      durationSeconds: 34,
      waveformPattern: [20, 40, 60, 85, 70, 55, 40, 65, 80, 60, 45, 35, 30, 25, 20],
    },
  },
];
