window.MOCK = {
  NEARBY_JOBS: [
    {
      id: 'J-1001',
      title: 'Kitchen Sink Drainage Blockage',
      category: 'Plumbing',
      categoryIcon: '🔧',
      description: 'Heavy kitchen sink drainage blockage with standing water. Standard plunger did not resolve. Need professional pipe cleaning or trap replacement before kitchen use.',
      distance: '2.1 km',
      area: 'F-11, Islamabad',
      exactAddress: 'House 88, Street 19, F-11/1, Islamabad',
      urgency: 'urgent',
      customerName: 'Tariq Mehmood',
      customerPhone: '+92 312 3456789',
      visitFee: 300,
      repairEstimate: 'Rs. 1,200 – Rs. 2,200',
      status: 'offer-sent',
      postedTime: '12 min ago',
      scheduledTime: 'Today, 4:00 PM',
    },
    {
      id: 'J-1002',
      title: 'AC Not Cooling — Compressor Noise',
      category: 'AC Repair',
      categoryIcon: '❄️',
      description: 'Split unit in living room stopped cooling after making loud noise. Compressor runs but temperature not dropping. Has been two days without AC in this heat.',
      distance: '3.4 km',
      area: 'G-9, Islamabad',
      exactAddress: 'Apartment 3B, Block 4, G-9/1, Islamabad',
      urgency: 'normal',
      customerName: 'Sara Khan',
      customerPhone: '+92 321 9876543',
      visitFee: 350,
      repairEstimate: 'Rs. 2,000 – Rs. 4,000',
      status: 'nearby',
      postedTime: '35 min ago',
      scheduledTime: 'Tomorrow, 11:00 AM',
    },
    {
      id: 'J-1003',
      title: 'Frequent Power Tripping — Kitchen',
      category: 'Electrician',
      categoryIcon: '⚡',
      description: 'MCB trips every time the microwave or kettle is used. Lights also flicker. Suspect overloaded circuit or faulty wiring behind the kitchen wall.',
      distance: '1.8 km',
      area: 'I-8, Islamabad',
      exactAddress: 'House 112, Street 5, I-8/3, Islamabad',
      urgency: 'urgent',
      customerName: 'Bilal Ahmed',
      customerPhone: '+92 333 4567890',
      visitFee: 280,
      repairEstimate: 'Rs. 800 – Rs. 1,800',
      status: 'nearby',
      postedTime: '1 hr ago',
      scheduledTime: 'Today, 6:30 PM',
    },
    {
      id: 'J-1004',
      title: 'Bathroom Ceiling Water Stain',
      category: 'Plumbing',
      categoryIcon: '🔧',
      description: 'Dark water stain on bathroom ceiling growing each day. Possibly pipe leakage from the apartment above. Need inspection and diagnosis.',
      distance: '4.2 km',
      area: 'E-11, Islamabad',
      exactAddress: 'Flat 502, Royal Heights, E-11/4, Islamabad',
      urgency: 'normal',
      customerName: 'Nadia Ali',
      customerPhone: '+92 345 6789012',
      visitFee: 300,
      repairEstimate: 'Rs. 1,000 – Rs. 3,000',
      status: 'nearby',
      postedTime: '2 hrs ago',
      scheduledTime: 'Tomorrow, 2:00 PM',
    },
  ],
  ACTIVE_JOB: {
    id: 'J-0998',
    title: 'Leaking Main Water Valve',
    category: 'Plumbing',
    categoryIcon: '🔧',
    description: 'Cracked 1-inch PVC elbow joint behind wall near main inlet. Needs replacement and pressure testing.',
    distance: '2.1 km',
    area: 'F-10, Islamabad',
    exactAddress: 'House 47, Street 12, F-10/2, Islamabad',
    urgency: 'urgent',
    customerName: 'Ahmed Raza',
    customerPhone: '+92 300 1234567',
    visitFee: 285,
    repairEstimate: 'Rs. 1,500 – Rs. 2,500',
    status: 'repair-approved',
    postedTime: '3 hrs ago',
    scheduledTime: 'Today, 4:00 PM',
    partsCost: 1200,
    laborCost: 1500,
    totalCost: 2985,
    workerPayout: 2537,
  },
  REVIEWS: [
    {
      id: 'R-001',
      customerName: 'Ahmed Raza',
      stars: 5,
      date: 'Sep 9, 2026',
      jobCategory: 'Plumbing',
      text: 'Usman arrived on time and diagnosed the problem quickly. The repair was clean and professional. Explained every step clearly. Would hire again without hesitation.',
      tags: ['Punctual', 'Professional', 'Transparent Pricing'],
    },
    {
      id: 'R-002',
      customerName: 'Sara Khan',
      stars: 5,
      date: 'Sep 7, 2026',
      jobCategory: 'AC Repair',
      text: 'Very experienced with AC systems. Diagnosed gas leak and compressor fault within minutes. Pricing was fair and itemized. No surprises.',
      tags: ['Expert', 'Fair Pricing', 'Clean Work'],
    },
    {
      id: 'R-003',
      customerName: 'Nadia Ali',
      stars: 4,
      date: 'Sep 5, 2026',
      jobCategory: 'Plumbing',
      text: 'Good work overall. Bathroom faucet is fixed. Took a bit longer than expected but the result is solid. Would recommend.',
      tags: ['Reliable', 'Thorough'],
    },
    {
      id: 'R-004',
      customerName: 'Hamid Ch.',
      stars: 5,
      date: 'Sep 3, 2026',
      jobCategory: 'Plumbing',
      text: 'Cleared a stubborn kitchen drain block in under 30 minutes. Brought proper equipment. Very professional attitude.',
      tags: ['Efficient', 'Well-Equipped'],
    },
    {
      id: 'R-005',
      customerName: 'Ayesha M.',
      stars: 4,
      date: 'Sep 1, 2026',
      jobCategory: 'Plumbing',
      text: 'Fixed the water tank float issue quickly. Price was reasonable. Cleaned up after himself which I really appreciated.',
      tags: ['Tidy', 'Courteous'],
    },
  ],
  COMPLETED_JOBS: [
    { id: 'J-0997', title: 'Leaking Main Valve', customer: 'Ahmed Raza', date: '10 Sep 2026', amount: 2537, rating: 5, category: 'Plumbing' },
    { id: 'J-0996', title: 'AC Gas Refill & Service', customer: 'Sara Khan', date: '08 Sep 2026', amount: 3400, rating: 5, category: 'AC Repair' },
    { id: 'J-0995', title: 'Bathroom Faucet Repair', customer: 'Nadia Ali', date: '05 Sep 2026', amount: 850, rating: 4, category: 'Plumbing' },
    { id: 'J-0994', title: 'Kitchen Drain Blockage', customer: 'Hamid Ch.', date: '02 Sep 2026', amount: 1200, rating: 5, category: 'Plumbing' },
    { id: 'J-0993', title: 'Water Tank Float Fix', customer: 'Ayesha M.', date: '29 Aug 2026', amount: 600, rating: 4, category: 'Plumbing' },
  ],
  CATEGORIES: [
    { id: 'plumbing', label: 'Plumbing', icon: '🔧' },
    { id: 'ac', label: 'AC Repair', icon: '❄️' },
    { id: 'electrical', label: 'Electrician', icon: '⚡' },
    { id: 'carpenter', label: 'Carpenter', icon: '🪚' },
    { id: 'appliance', label: 'Appliance Repair', icon: '🛠️' },
    { id: 'painter', label: 'Painter', icon: '🖌️' },
    { id: 'cleaning', label: 'Cleaning', icon: '🧹' },
    { id: 'other', label: 'Other Services', icon: '📦' },
  ],
  SUB_SKILLS: {
    plumbing: ['Pipe Fitting', 'Leak Repair', 'Drain Cleaning', 'Water Heater', 'Tank Installation'],
    ac: ['Installation', 'Gas Refilling', 'Servicing & Cleaning', 'Compressor Repair', 'Thermostat Repair'],
    electrical: ['Wiring', 'MCB / Fuse Box', 'Fan / Light Installation', 'Inverter Setup', 'CCTV Wiring'],
    carpenter: ['Door Fitting', 'Furniture Assembly', 'Cabinet Making', 'Wood Polish', 'Kitchen Cabinets'],
    appliance: ['Washing Machine', 'Refrigerator', 'Microwave', 'Dishwasher', 'Generator'],
    painter: ['Interior Painting', 'Exterior Painting', 'Wall Texture', 'Wood Polish', 'Waterproofing'],
    cleaning: ['Deep Cleaning', 'Sofa Cleaning', 'Carpet Cleaning', 'After-Construction', 'Tank Cleaning'],
    other: [],
  },
  DISPUTES: [
    {
      id: 'DSP-041',
      jobId: 'J-0982',
      customer: 'Kamran Tariq',
      date: '28 Aug 2026',
      reason: 'Customer requested work outside original scope without additional payment.',
      status: 'Resolved in worker favor',
      statusType: 'resolved',
      resolution: 'Hunar admin reviewed chat logs and released escrow payout of Rs. 1,800 to worker.',
    },
  ],
  WORKER_PROFILE: {
    name: 'Usman Malik',
    trade: 'Plumber & Pipe Specialist',
    experience: 8,
    visitFee: 300,
    phone: '+92 321 1234567',
    cnic: '61101-2345678-9',
    city: 'F-10, Islamabad',
    radius: 10,
    bio: 'Licensed plumber with 8 years of residential and commercial experience in Islamabad. Specialise in pipe fitting, leak repair, drainage, and water heater installation.',
    rating: 4.8,
    reviewsCount: 94,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&h=160&fit=crop',
    verified: true,
  },
};
